// Generated from actual sram512.sch Xschem netlist; functional verification only.
`timescale 1ns/1ps
`default_nettype none
module sram512_digital_gates(input wire CLK, RESET, SDI, WE, SOUT,
output wire SDO, PREB, SAE, WL_EN, WRITE_EN, DIN, PD_Y, PD_YB,
output wire [3:0] RA, output wire [4:0] CA, COUNT,
output wire [15:0] WL, output wire [31:0] COL);
reg n_ca0,n_ca1,n_ca2,n_ca3,n_ca4,n_din,n_ra0,n_ra1,n_ra2,n_ra3,n_wl_en,n_write_en,n_xctrl__read_data,n_xctrl__xcontrol__pc_on,n_xctrl__xcontrol__track,n_xctrl__xcontrol__w,n_xctrl__xphase__c0,n_xctrl__xphase__c1,n_xctrl__xphase__c2,n_xctrl__xphase__c3,n_xctrl__xphase__c4;
wire n_ca0b,n_ca1b,n_ca2b,n_ca3b,n_ca4b,n_clk,n_col0,n_col1,n_col10,n_col11,n_col12,n_col13,n_col14,n_col15,n_col16,n_col17,n_col18,n_col19,n_col2,n_col20,n_col21,n_col22,n_col23,n_col24,n_col25,n_col26,n_col27,n_col28,n_col29,n_col3,n_col30,n_col31,n_col4,n_col5,n_col6,n_col7,n_col8,n_col9,n_dinb,n_pd_y,n_pd_yb,n_preb,n_ra0b,n_ra1b,n_ra2b,n_ra3b,n_reset,n_sae,n_sdi,n_sdo,n_sout,n_vdd,n_vss,n_we,n_wl0,n_wl1,n_wl10,n_wl11,n_wl12,n_wl13,n_wl14,n_wl15,n_wl2,n_wl3,n_wl4,n_wl5,n_wl6,n_wl7,n_wl8,n_wl9,n_xcol_decode__ch0,n_xcol_decode__ch1,n_xcol_decode__ch2,n_xcol_decode__ch3,n_xcol_decode__ch4,n_xcol_decode__ch5,n_xcol_decode__ch6,n_xcol_decode__ch7,n_xcol_decode__cl0,n_xcol_decode__cl1,n_xcol_decode__cl2,n_xcol_decode__cl3,n_xctrl__cki,n_xctrl__e0,n_xctrl__e1,n_xctrl__e2,n_xctrl__e3,n_xctrl__e4,n_xctrl__e5,n_xctrl__e6,n_xctrl__e7,n_xctrl__preb_i,n_xctrl__rsti,n_xctrl__rx,n_xctrl__sae_i,n_xctrl__xcontrol__net1,n_xctrl__xcontrol__net2,n_xctrl__xcontrol__read_capture,n_xctrl__xcontrol__read_datab,n_xctrl__xcontrol__track_d,n_xctrl__xcontrol__track_first,n_xctrl__xcontrol__track_later,n_xctrl__xcontrol__track_window,n_xctrl__xcontrol__wb,n_xctrl__xcontrol__we_b,n_xctrl__xcontrol__wl_d,n_xctrl__xcontrol__wl_enb,n_xctrl__xcontrol__write_d,n_xctrl__xcontrol__write_enb,n_xctrl__xcontrol__write_window,n_xctrl__xframe__net1,n_xctrl__xframe__net10,n_xctrl__xframe__net2,n_xctrl__xframe__net3,n_xctrl__xframe__net4,n_xctrl__xframe__net5,n_xctrl__xframe__net6,n_xctrl__xframe__net7,n_xctrl__xframe__net8,n_xctrl__xframe__net9,n_xctrl__xphase__c0b,n_xctrl__xphase__c1b,n_xctrl__xphase__c2b,n_xctrl__xphase__c3b,n_xctrl__xphase__c4b,n_xctrl__xphase__carry2,n_xctrl__xphase__carry3,n_xctrl__xphase__carry4,n_xctrl__xphase__count_run,n_xctrl__xphase__e0_low,n_xctrl__xphase__e1_low,n_xctrl__xphase__e2_low,n_xctrl__xphase__e3_low,n_xctrl__xphase__e4_low,n_xctrl__xphase__e5_low,n_xctrl__xphase__e6_low,n_xctrl__xphase__e7_low,n_xctrl__xphase__low_zero,n_xctrl__xphase__next0,n_xctrl__xphase__next1,n_xctrl__xphase__next2,n_xctrl__xphase__next3,n_xctrl__xphase__next4,n_xctrl__xphase__rx_low,n_xctrl__xphase__rx_upper,n_xctrl__xphase__toggle1,n_xctrl__xphase__toggle2,n_xctrl__xphase__toggle3,n_xctrl__xphase__toggle4,n_xrow__r0_0,n_xrow__r0_1,n_xrow__r0_2,n_xrow__r0_3,n_xrow__r1_0,n_xrow__r1_1,n_xrow__r1_2,n_xrow__r1_3,n_xrow__ra0b,n_xrow__ra1b,n_xrow__ra2b,n_xrow__ra3b;
assign n_clk=CLK;
assign n_reset=RESET;
assign n_sdi=SDI;
assign n_we=WE;
assign n_sout=SOUT;
assign n_vdd=1'b1;
assign n_vss=1'b0;
assign n_xrow__ra0b=~n_ra0;
assign n_xrow__ra1b=~n_ra1;
assign n_xrow__ra2b=~n_ra2;
assign n_xrow__ra3b=~n_ra3;
assign n_xrow__r0_0=(n_xrow__ra0b&n_xrow__ra1b);
assign n_xrow__r0_1=(n_ra0&n_xrow__ra1b);
assign n_xrow__r0_2=(n_xrow__ra0b&n_ra1);
assign n_xrow__r0_3=(n_ra0&n_ra1);
assign n_xrow__r1_0=(n_xrow__ra2b&n_xrow__ra3b);
assign n_xrow__r1_1=(n_ra2&n_xrow__ra3b);
assign n_xrow__r1_2=(n_xrow__ra2b&n_ra3);
assign n_xrow__r1_3=(n_ra2&n_ra3);
assign n_wl0=(n_xrow__r0_0&n_xrow__r1_0&n_wl_en);
assign n_wl1=(n_xrow__r0_1&n_xrow__r1_0&n_wl_en);
assign n_wl2=(n_xrow__r0_2&n_xrow__r1_0&n_wl_en);
assign n_wl3=(n_xrow__r0_3&n_xrow__r1_0&n_wl_en);
assign n_wl4=(n_xrow__r0_0&n_xrow__r1_1&n_wl_en);
assign n_wl5=(n_xrow__r0_1&n_xrow__r1_1&n_wl_en);
assign n_wl6=(n_xrow__r0_2&n_xrow__r1_1&n_wl_en);
assign n_wl7=(n_xrow__r0_3&n_xrow__r1_1&n_wl_en);
assign n_wl8=(n_xrow__r0_0&n_xrow__r1_2&n_wl_en);
assign n_wl9=(n_xrow__r0_1&n_xrow__r1_2&n_wl_en);
assign n_wl10=(n_xrow__r0_2&n_xrow__r1_2&n_wl_en);
assign n_wl11=(n_xrow__r0_3&n_xrow__r1_2&n_wl_en);
assign n_wl12=(n_xrow__r0_0&n_xrow__r1_3&n_wl_en);
assign n_wl13=(n_xrow__r0_1&n_xrow__r1_3&n_wl_en);
assign n_wl14=(n_xrow__r0_2&n_xrow__r1_3&n_wl_en);
assign n_wl15=(n_xrow__r0_3&n_xrow__r1_3&n_wl_en);
assign n_xcol_decode__cl0=(n_ca0b&n_ca1b);
assign n_xcol_decode__cl1=(n_ca0&n_ca1b);
assign n_xcol_decode__cl2=(n_ca0b&n_ca1);
assign n_xcol_decode__cl3=(n_ca0&n_ca1);
assign n_xcol_decode__ch0=(n_ca2b&n_ca3b&n_ca4b);
assign n_xcol_decode__ch1=(n_ca2&n_ca3b&n_ca4b);
assign n_xcol_decode__ch2=(n_ca2b&n_ca3&n_ca4b);
assign n_xcol_decode__ch3=(n_ca2&n_ca3&n_ca4b);
assign n_xcol_decode__ch4=(n_ca2b&n_ca3b&n_ca4);
assign n_xcol_decode__ch5=(n_ca2&n_ca3b&n_ca4);
assign n_xcol_decode__ch6=(n_ca2b&n_ca3&n_ca4);
assign n_xcol_decode__ch7=(n_ca2&n_ca3&n_ca4);
assign n_col0=(n_xcol_decode__cl0&n_xcol_decode__ch0);
assign n_col1=(n_xcol_decode__cl1&n_xcol_decode__ch0);
assign n_col2=(n_xcol_decode__cl2&n_xcol_decode__ch0);
assign n_col3=(n_xcol_decode__cl3&n_xcol_decode__ch0);
assign n_col4=(n_xcol_decode__cl0&n_xcol_decode__ch1);
assign n_col5=(n_xcol_decode__cl1&n_xcol_decode__ch1);
assign n_col6=(n_xcol_decode__cl2&n_xcol_decode__ch1);
assign n_col7=(n_xcol_decode__cl3&n_xcol_decode__ch1);
assign n_col8=(n_xcol_decode__cl0&n_xcol_decode__ch2);
assign n_col9=(n_xcol_decode__cl1&n_xcol_decode__ch2);
assign n_col10=(n_xcol_decode__cl2&n_xcol_decode__ch2);
assign n_col11=(n_xcol_decode__cl3&n_xcol_decode__ch2);
assign n_col12=(n_xcol_decode__cl0&n_xcol_decode__ch3);
assign n_col13=(n_xcol_decode__cl1&n_xcol_decode__ch3);
assign n_col14=(n_xcol_decode__cl2&n_xcol_decode__ch3);
assign n_col15=(n_xcol_decode__cl3&n_xcol_decode__ch3);
assign n_col16=(n_xcol_decode__cl0&n_xcol_decode__ch4);
assign n_col17=(n_xcol_decode__cl1&n_xcol_decode__ch4);
assign n_col18=(n_xcol_decode__cl2&n_xcol_decode__ch4);
assign n_col19=(n_xcol_decode__cl3&n_xcol_decode__ch4);
assign n_col20=(n_xcol_decode__cl0&n_xcol_decode__ch5);
assign n_col21=(n_xcol_decode__cl1&n_xcol_decode__ch5);
assign n_col22=(n_xcol_decode__cl2&n_xcol_decode__ch5);
assign n_col23=(n_xcol_decode__cl3&n_xcol_decode__ch5);
assign n_col24=(n_xcol_decode__cl0&n_xcol_decode__ch6);
assign n_col25=(n_xcol_decode__cl1&n_xcol_decode__ch6);
assign n_col26=(n_xcol_decode__cl2&n_xcol_decode__ch6);
assign n_col27=(n_xcol_decode__cl3&n_xcol_decode__ch6);
assign n_col28=(n_xcol_decode__cl0&n_xcol_decode__ch7);
assign n_col29=(n_xcol_decode__cl1&n_xcol_decode__ch7);
assign n_col30=(n_xcol_decode__cl2&n_xcol_decode__ch7);
assign n_col31=(n_xcol_decode__cl3&n_xcol_decode__ch7);
assign n_pd_y=(n_dinb&n_write_en);
assign n_pd_yb=(n_din&n_write_en);
assign n_xctrl__cki=n_clk;
assign n_xctrl__rsti=n_reset;
assign n_xctrl__xphase__low_zero=(n_xctrl__xphase__c0b&n_xctrl__xphase__c1b&n_xctrl__xphase__c2b&n_xctrl__xphase__c3b);
assign n_xctrl__xphase__count_run=(n_xctrl__xphase__c4b|n_xctrl__xphase__low_zero);
assign n_xctrl__xphase__next0=(n_xctrl__xphase__c0b&n_xctrl__xphase__count_run);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xphase__c0<=0; else n_xctrl__xphase__c0<=n_xctrl__xphase__next0;
assign n_xctrl__xphase__c0b=~n_xctrl__xphase__c0;
assign n_xctrl__xphase__toggle1=(n_xctrl__xphase__c1^n_xctrl__xphase__c0);
assign n_xctrl__xphase__next1=(n_xctrl__xphase__toggle1&n_xctrl__xphase__count_run);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xphase__c1<=0; else n_xctrl__xphase__c1<=n_xctrl__xphase__next1;
assign n_xctrl__xphase__c1b=~n_xctrl__xphase__c1;
assign n_xctrl__xphase__carry2=(n_xctrl__xphase__c0&n_xctrl__xphase__c1);
assign n_xctrl__xphase__toggle2=(n_xctrl__xphase__c2^n_xctrl__xphase__carry2);
assign n_xctrl__xphase__next2=(n_xctrl__xphase__toggle2&n_xctrl__xphase__count_run);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xphase__c2<=0; else n_xctrl__xphase__c2<=n_xctrl__xphase__next2;
assign n_xctrl__xphase__c2b=~n_xctrl__xphase__c2;
assign n_xctrl__xphase__carry3=(n_xctrl__xphase__c0&n_xctrl__xphase__c1&n_xctrl__xphase__c2);
assign n_xctrl__xphase__toggle3=(n_xctrl__xphase__c3^n_xctrl__xphase__carry3);
assign n_xctrl__xphase__next3=(n_xctrl__xphase__toggle3&n_xctrl__xphase__count_run);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xphase__c3<=0; else n_xctrl__xphase__c3<=n_xctrl__xphase__next3;
assign n_xctrl__xphase__c3b=~n_xctrl__xphase__c3;
assign n_xctrl__xphase__carry4=(n_xctrl__xphase__c0&n_xctrl__xphase__c1&n_xctrl__xphase__c2&n_xctrl__xphase__c3);
assign n_xctrl__xphase__toggle4=(n_xctrl__xphase__c4^n_xctrl__xphase__carry4);
assign n_xctrl__xphase__next4=(n_xctrl__xphase__toggle4&n_xctrl__xphase__count_run);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xphase__c4<=0; else n_xctrl__xphase__c4<=n_xctrl__xphase__next4;
assign n_xctrl__xphase__c4b=~n_xctrl__xphase__c4;
assign n_xctrl__xphase__e0_low=(n_xctrl__xphase__c0b&n_xctrl__xphase__c1&n_xctrl__xphase__c2b&n_xctrl__xphase__c3);
assign n_xctrl__e0=(n_xctrl__xphase__e0_low&n_xctrl__xphase__c4b);
assign n_xctrl__xphase__e1_low=(n_xctrl__xphase__c0&n_xctrl__xphase__c1&n_xctrl__xphase__c2b&n_xctrl__xphase__c3);
assign n_xctrl__e1=(n_xctrl__xphase__e1_low&n_xctrl__xphase__c4b);
assign n_xctrl__xphase__e2_low=(n_xctrl__xphase__c0b&n_xctrl__xphase__c1b&n_xctrl__xphase__c2&n_xctrl__xphase__c3);
assign n_xctrl__e2=(n_xctrl__xphase__e2_low&n_xctrl__xphase__c4b);
assign n_xctrl__xphase__e3_low=(n_xctrl__xphase__c0&n_xctrl__xphase__c1b&n_xctrl__xphase__c2&n_xctrl__xphase__c3);
assign n_xctrl__e3=(n_xctrl__xphase__e3_low&n_xctrl__xphase__c4b);
assign n_xctrl__xphase__e4_low=(n_xctrl__xphase__c0b&n_xctrl__xphase__c1&n_xctrl__xphase__c2&n_xctrl__xphase__c3);
assign n_xctrl__e4=(n_xctrl__xphase__e4_low&n_xctrl__xphase__c4b);
assign n_xctrl__xphase__e5_low=(n_xctrl__xphase__c0&n_xctrl__xphase__c1&n_xctrl__xphase__c2&n_xctrl__xphase__c3);
assign n_xctrl__e5=(n_xctrl__xphase__e5_low&n_xctrl__xphase__c4b);
assign n_xctrl__xphase__e6_low=(n_xctrl__xphase__c0b&n_xctrl__xphase__c1b&n_xctrl__xphase__c2b&n_xctrl__xphase__c3b);
assign n_xctrl__e6=(n_xctrl__xphase__e6_low&n_xctrl__xphase__c4);
assign n_xctrl__xphase__e7_low=(n_xctrl__xphase__c0&n_xctrl__xphase__c1b&n_xctrl__xphase__c2b&n_xctrl__xphase__c3b);
assign n_xctrl__e7=(n_xctrl__xphase__e7_low&n_xctrl__xphase__c4);
assign n_xctrl__xphase__rx_low=(n_xctrl__xphase__c2b&n_xctrl__xphase__c1b);
assign n_xctrl__xphase__rx_upper=(n_xctrl__xphase__c3b|n_xctrl__xphase__rx_low);
assign n_xctrl__rx=(n_xctrl__xphase__c4b&n_xctrl__xphase__rx_upper);
assign n_xctrl__xframe__net1=n_xctrl__rx?n_sdi:n_din;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_din<=0; else n_din<=n_xctrl__xframe__net1;
assign n_dinb=~n_din;
assign n_xctrl__xframe__net2=n_xctrl__rx?n_din:n_ca0;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ca0<=0; else n_ca0<=n_xctrl__xframe__net2;
assign n_ca0b=~n_ca0;
assign n_xctrl__xframe__net3=n_xctrl__rx?n_ca0:n_ca1;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ca1<=0; else n_ca1<=n_xctrl__xframe__net3;
assign n_ca1b=~n_ca1;
assign n_xctrl__xframe__net4=n_xctrl__rx?n_ca1:n_ca2;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ca2<=0; else n_ca2<=n_xctrl__xframe__net4;
assign n_ca2b=~n_ca2;
assign n_xctrl__xframe__net5=n_xctrl__rx?n_ca2:n_ca3;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ca3<=0; else n_ca3<=n_xctrl__xframe__net5;
assign n_ca3b=~n_ca3;
assign n_xctrl__xframe__net6=n_xctrl__rx?n_ca3:n_ca4;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ca4<=0; else n_ca4<=n_xctrl__xframe__net6;
assign n_ca4b=~n_ca4;
assign n_xctrl__xframe__net7=n_xctrl__rx?n_ca4:n_ra0;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ra0<=0; else n_ra0<=n_xctrl__xframe__net7;
assign n_ra0b=~n_ra0;
assign n_xctrl__xframe__net8=n_xctrl__rx?n_ra0:n_ra1;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ra1<=0; else n_ra1<=n_xctrl__xframe__net8;
assign n_ra1b=~n_ra1;
assign n_xctrl__xframe__net9=n_xctrl__rx?n_ra1:n_ra2;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ra2<=0; else n_ra2<=n_xctrl__xframe__net9;
assign n_ra2b=~n_ra2;
assign n_xctrl__xframe__net10=n_xctrl__rx?n_ra2:n_ra3;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_ra3<=0; else n_ra3<=n_xctrl__xframe__net10;
assign n_ra3b=~n_ra3;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xcontrol__pc_on<=0; else n_xctrl__xcontrol__pc_on<=n_xctrl__e0;
assign n_xctrl__preb_i=~n_xctrl__xcontrol__pc_on;
assign n_xctrl__xcontrol__wl_d=(n_xctrl__e3|n_xctrl__e4);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_wl_en<=0; else n_wl_en<=n_xctrl__xcontrol__wl_d;
assign n_xctrl__xcontrol__wl_enb=~n_wl_en;
assign n_xctrl__xcontrol__write_window=(n_xctrl__e2|n_xctrl__e3|n_xctrl__e4|n_xctrl__e5);
assign n_xctrl__xcontrol__write_d=(n_xctrl__xcontrol__write_window&n_xctrl__xcontrol__w);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_write_en<=0; else n_write_en<=n_xctrl__xcontrol__write_d;
assign n_xctrl__xcontrol__write_enb=~n_write_en;
assign n_xctrl__xcontrol__we_b=~n_we;
assign n_xctrl__xcontrol__track_first=(n_xctrl__xcontrol__we_b&n_xctrl__e0);
assign n_xctrl__xcontrol__track_window=(n_xctrl__e1|n_xctrl__e2|n_xctrl__e3);
assign n_xctrl__xcontrol__track_later=(n_xctrl__xcontrol__track_window&n_xctrl__xcontrol__wb);
assign n_xctrl__xcontrol__track_d=(n_xctrl__xcontrol__track_first|n_xctrl__xcontrol__track_later);
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xcontrol__track<=0; else n_xctrl__xcontrol__track<=n_xctrl__xcontrol__track_d;
assign n_xctrl__sae_i=~n_xctrl__xcontrol__track;
assign n_xctrl__xcontrol__net1=n_xctrl__e0?n_we:n_xctrl__xcontrol__w;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__xcontrol__w<=0; else n_xctrl__xcontrol__w<=n_xctrl__xcontrol__net1;
assign n_xctrl__xcontrol__wb=~n_xctrl__xcontrol__w;
assign n_xctrl__xcontrol__read_capture=(n_xctrl__e6&n_xctrl__xcontrol__wb);
assign n_xctrl__xcontrol__net2=n_xctrl__xcontrol__read_capture?n_sout:n_xctrl__read_data;
always @(posedge n_xctrl__cki or posedge n_xctrl__rsti) if (n_xctrl__rsti) n_xctrl__read_data<=0; else n_xctrl__read_data<=n_xctrl__xcontrol__net2;
assign n_xctrl__xcontrol__read_datab=~n_xctrl__read_data;
assign n_preb=n_xctrl__preb_i;
assign n_sae=n_xctrl__sae_i;
assign n_sdo=n_xctrl__read_data;
assign SDO=n_sdo;
assign PREB=n_preb;
assign SAE=n_sae;
assign WL_EN=n_wl_en;
assign WRITE_EN=n_write_en;
assign DIN=n_din;
assign PD_Y=n_pd_y;
assign PD_YB=n_pd_yb;
assign RA={n_ra3,n_ra2,n_ra1,n_ra0};
assign CA={n_ca4,n_ca3,n_ca2,n_ca1,n_ca0};
assign WL={n_wl15,n_wl14,n_wl13,n_wl12,n_wl11,n_wl10,n_wl9,n_wl8,n_wl7,n_wl6,n_wl5,n_wl4,n_wl3,n_wl2,n_wl1,n_wl0};
assign COL={n_col31,n_col30,n_col29,n_col28,n_col27,n_col26,n_col25,n_col24,n_col23,n_col22,n_col21,n_col20,n_col19,n_col18,n_col17,n_col16,n_col15,n_col14,n_col13,n_col12,n_col11,n_col10,n_col9,n_col8,n_col7,n_col6,n_col5,n_col4,n_col3,n_col2,n_col1,n_col0};
assign COUNT={n_xctrl__xphase__c4,n_xctrl__xphase__c3,n_xctrl__xphase__c2,n_xctrl__xphase__c1,n_xctrl__xphase__c0};
endmodule
`default_nettype wire
