#!/usr/bin/env python3
"""Exact A coordinate encoding and mask factorization trials (core only)."""
import argparse
import hashlib
import json
from pathlib import Path
from a_logo_trial import ROOT, SOURCE, BASE, PALETTE, reference, raw_range


def generate(start, axis, vertical=500):
    assert 0 <= start <= 255 and vertical in (0, 500)
    name = f'a_h{start}_v{vertical}_{axis}'
    design = ROOT / 'experiments' / name
    assert not (design / 'out').exists(), 'Do not overwrite a built trial'
    for sub in ('build', 'tests'):
        (design / sub).mkdir(parents=True, exist_ok=True)
    rects = json.loads(SOURCE.read_text())
    reference(rects, design)

    def hor(a, b):
        lo, hi = (start - b + 1) % 256, (start - a + 1) % 256
        if lo < hi:
            return raw_range('h', lo, hi)
        if hi == 0:
            return raw_range('h', lo, 256)
        return '(' + raw_range('h', lo, 256) + ' | ' + raw_range('h', 0, hi) + ')'

    def interval(which, a, b):
        return hor(a + 16, b + 16) if which == 'h' else raw_range('y', a + 6 + vertical // 4, b + 6 + vertical // 4)

    # Only constant encodings change. No coordinate subtractor is synthesized.
    core = (BASE / 'ishi_vga_core.v').read_text()
    for old, new in [
        ("h <= 8'd79", f"h <= 8'd{start}"),
        ("h == 8'd136", f"h == 8'd{(start - 199) % 256}"),
        ("((h >= 8'd176) || (h < 8'd80))", hor(0, 160)),
        ("((h >= 8'd148) && (h < 8'd172))", hor(164, 188)),
    ]:
        assert old in core
        core = core.replace(old, new)
    if vertical == 0:
        for old, new in [
            ("v <= 10'd500;", "v <= 10'd0;"),
            ("(v == 10'd0) ? 10'd500", "(v == 10'd524) ? 10'd0"),
            ("((v >= 10'd500) && (v < 10'd980))", "(v < 10'd480)"),
            ("((v >= 10'd990) && (v < 10'd992))", "((v >= 10'd490) && (v < 10'd492))"),
        ]:
            assert old in core
            core = core.replace(old, new)
    (design / 'ishi_vga_core.v').write_text(core)
    lines = ['// Generated by scripts/a_counter_trial.py; corrected A image.',
             '`default_nettype none',
             'module ishi_logo(input wire [7:0] h,y, output wire [5:0] rgb);']
    for color in [4, 5, 1, 2, 3]:
        groups = {}
        for co, a, b, c, d in rects:
            if co == color:
                key, value = ((a, c), (b, d)) if axis == 'x' else ((b, d), (a, c))
                groups.setdefault(key, []).append(value)
        first, second = ('h', 'y') if axis == 'x' else ('y', 'h')
        terms = ['(' + interval(first, *key) + ' & (' + ' | '.join(interval(second, *v) for v in values) + '))'
                 for key, values in groups.items()]
        lines.append(f'wire color_{color} = ' + ' |\n    '.join(terms) + ';')
    lines.append('assign rgb = ' + ' : '.join(f'color_{c} ? 6\'d{PALETTE[c]}' for c in [3, 2, 1, 5, 4]) + " : 6'd63;")
    lines.extend(['endmodule', '`default_nettype wire', ''])
    (design / 'ishi_logo.v').write_text('\n'.join(lines))
    (design / 'config.py').write_bytes((ROOT / 'experiments/a_group_y/config.py').read_bytes())
    paths = [Path(__file__), ROOT / 'scripts/a_logo_trial.py', SOURCE, ROOT / 'toolchain.lock.json',
             design / 'ishi_vga_core.v', design / 'ishi_logo.v', design / 'config.py', design / 'tests/expected_frame.hex']
    (design / 'source_manifest.json').write_text(json.dumps({
        'name': name, 'h_start': start, 'v_start': vertical, 'group_axis': axis,
        'sha256': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}
    }, indent=2) + '\n')
    print(name, flush=True)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('start', type=int)
    ap.add_argument('axis', choices=['x', 'y'])
    ap.add_argument('--vertical', type=int, default=500)
    a = ap.parse_args()
    generate(a.start, a.axis, a.vertical)
