#!/usr/bin/env python3
"""Corrected A image experiments. Never overwrites the accepted B design.

Generate exact combinational alternatives on the proven h=79 descending,
v=500 offset counters. The reference painter uses ordinary screen coordinates.
"""
import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/logo_rectangles_a_corrected.json'
BASE = ROOT / 'experiments/descending_h79_v500'
PALETTE = [63, 27, 53, 31, 23, 43]
MODES = ['rect_bounds', 'rect_masked', 'group_y', 'rgb_runs', 'rgb_masked', 'espresso_rgb']


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def spans(values):
    """Half-open runs of identical values."""
    start = 0
    for end in range(1, len(values) + 1):
        if end == len(values) or values[end] != values[start]:
            yield start, end, values[start]
            start = end


def covers(a, b):
    while a < b:
        size = (a & -a) if a else 256
        while a + size > b:
            size //= 2
        yield a, 256 - size
        a += size


def raw_range(axis, a, b, masked=False):
    if a == 0 and b == 256:
        return "1'b1"
    if masked:
        return '(' + ' | '.join(f"(({axis} & 8'd{m}) == 8'd{v})" for v, m in covers(a, b)) + ')'
    if a == 0:
        return f"({axis} < 8'd{b})"
    if b == 256:
        return f"({axis} >= 8'd{a})"
    return f"(({axis} >= 8'd{a}) && ({axis} < 8'd{b}))"


def interval(axis, a, b, masked=False):
    # Input intervals are unshifted logo coordinates.
    if axis == 'y':
        return raw_range(axis, a + 131, b + 131, masked)
    lo, hi = (64 - b) % 256, (64 - a) % 256
    if lo < hi:
        return raw_range(axis, lo, hi, masked)
    if hi == 0:
        return raw_range(axis, lo, 256, masked)
    return '(' + raw_range(axis, lo, 256, masked) + ' | ' + raw_range(axis, 0, hi, masked) + ')'


def reference(rects, design):
    import numpy as np
    from PIL import Image
    logo = np.zeros((108, 128), dtype=np.uint8)
    for c, x0, y0, x1, y1 in rects:
        logo[y0:y1, x0:x1] = c
    screen = np.full((480, 160), 63, dtype=np.uint8)
    screen[24:456, 16:144] = np.repeat(np.array(PALETTE, dtype=np.uint8)[logo], 4, axis=0)
    frame = np.zeros((525, 200), dtype=np.uint8)
    frame[:480, :160] = screen
    frame[:, :164] |= 64
    frame[:, 188:] |= 64
    frame[:490, :] |= 128
    frame[492:, :] |= 128
    (design / 'tests/expected_frame.hex').write_text(''.join(f'{v:02x}\n' for v in frame.flat))
    rgb = np.stack([((screen >> 4) & 3) * 85, ((screen >> 2) & 3) * 85, (screen & 3) * 85], axis=-1)
    Image.fromarray(np.repeat(rgb, 4, axis=1)).save(design / 'build/reference.png')
    return logo.tolist()


def generate(mode):
    design = ROOT / 'experiments' / ('a_' + mode)
    if (design / 'out/ishi_vga_core_pnr.v').exists():
        raise RuntimeError(f'refusing to regenerate already synthesized {design}')
    for sub in ('build', 'tests'):
        (design / sub).mkdir(parents=True, exist_ok=True)
    rects = json.loads(SOURCE.read_text())
    assert len(rects) == 37
    assert [1, 25, 62, 46, 65] in rects and [1, 11, 62, 46, 65] not in rects
    assert all(0 <= a < c <= 128 and 0 <= b < d <= 108 for _, a, b, c, d in rects)
    pixels = reference(rects, design)
    lines = ['// Corrected A; generated by scripts/a_logo_trial.py: ' + mode,
             '`default_nettype none',
             'module ishi_logo(input wire [7:0] h,y, output wire [5:0] rgb);']
    if mode.startswith('rect_') or mode == 'group_y':
        for color in [4, 5, 1, 2, 3]:
            if mode == 'group_y':
                groups = {}
                for co, a, b, c, d in rects:
                    if co == color:
                        groups.setdefault((b, d), []).append((a, c))
                terms = ['(' + interval('y', *k) + ' & (' + ' | '.join(interval('h', *x) for x in xs) + '))'
                         for k, xs in groups.items()]
            else:
                terms = ['(' + interval('h', a, c, mode == 'rect_masked') + ' & ' + interval('y', b, d, mode == 'rect_masked') + ')'
                         for co, a, b, c, d in rects if co == color]
            lines.append(f'wire color_{color} = ' + ' |\n    '.join(terms) + ';')
        # General priority decode: A has extra blue metal crossing the dark bands.
        # The B-only direct RGB identity must NOT be reused here.
        lines.append('assign rgb = ' + ' : '.join(f'color_{c} ? 6\'d{PALETTE[c]}' for c in [3, 2, 1, 5, 4]) + " : 6'd63;")
    else:
        bit_runs = []
        for bit in range(1, 6):
            groups = {}
            for yy, row in enumerate(pixels):
                for a, b, low in spans([not (PALETTE[c] & (1 << bit)) for c in row]):
                    if low:
                        groups.setdefault((a, b), []).append(yy)
            bit_runs.append(groups)
        if mode == 'espresso_rgb':
            sys.path.insert(0, str(ROOT / '.tools/logic_pyeda'))
            from pyeda.inter import exprvars, And, Or, espresso_exprs
            hv, yv = exprvars('h', 8), exprvars('y', 8)

            def erange(v, a, b):
                return Or(*[And(*[(v[i] if value & (1 << i) else ~v[i]) for i in range(8) if mask & (1 << i)])
                            for value, mask in covers(a, b)])

            def ehor(a, b):
                lo, hi = (64 - b) % 256, (64 - a) % 256
                return erange(hv, lo, hi) if lo < hi else Or(erange(hv, lo, 256), erange(hv, 0, hi))

            expressions = []
            for groups in bit_runs:
                terms = []
                for (a, b), ys in groups.items():
                    for c, d, val in spans([y in ys for y in range(108)]):
                        if val:
                            terms.append(ehor(a, b) & erange(yv, c + 131, d + 131))
                expressions.append(Or(*terms).to_dnf())

            def verilog(e):
                if e.is_zero(): return "1'b0"
                if e.is_one(): return "1'b1"
                s = str(e)
                if s.startswith('Or('): return '(' + ' | '.join(verilog(x) for x in e.xs) + ')'
                if s.startswith('And('): return '(' + ' & '.join(verilog(x) for x in e.xs) + ')'
                return s

            for bit, e in enumerate(espresso_exprs(*expressions), 1):
                lines.append(f'assign rgb[{bit}] = ~{verilog(e)};')
        else:
            for bit, groups in enumerate(bit_runs, 1):
                terms = []
                for (a, b), ys in groups.items():
                    yterms = [interval('y', c, d, mode == 'rgb_masked')
                              for c, d, val in spans([y in ys for y in range(108)]) if val]
                    terms.append('(' + interval('h', a, b, mode == 'rgb_masked') + ' & (' + ' | '.join(yterms) + '))')
                lines.append(f'assign rgb[{bit}] = ~(' + ' |\n    '.join(terms) + ');')
        lines.append("assign rgb[0] = 1'b1;")
    lines.extend(['endmodule', '`default_nettype wire', ''])
    (design / 'ishi_logo.v').write_text('\n'.join(lines))
    (design / 'ishi_vga_core.v').write_bytes((BASE / 'ishi_vga_core.v').read_bytes())
    config = (ROOT / 'experiments/phys_desc5/config.py').read_text()
    config = '"""Corrected A trial; core only. No frame integration. Mode: ' + mode + '."""\n' + config
    (design / 'config.py').write_text(config)
    manifest = {'mode': mode, 'source': str(SOURCE.relative_to(ROOT)), 'rectangles': len(rects),
                'counter_source': str(BASE.relative_to(ROOT)), 'sha256': {
                    str(p.relative_to(ROOT)): sha(p) for p in [SOURCE, ROOT / 'toolchain.lock.json',
                    Path(__file__), design / 'config.py', design / 'ishi_vga_core.v', design / 'ishi_logo.v',
                    design / 'tests/expected_frame.hex']}}
    (design / 'source_manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(design.relative_to(ROOT), flush=True)


def verify(name):
    design = ROOT / 'experiments' / name
    assert name.startswith('a_') and '/' not in name
    expected = (design / 'tests/expected_frame.hex').read_bytes()
    checks, logs = [], []
    paths = [design / f for f in ('config.py', 'ishi_logo.v', 'ishi_vga_core.v',
             'out/ishi_vga_core_pnr.v', 'build/tr1um_cells.v', 'tests/expected_frame.hex')]
    for model, sources in [('rtl', paths[1:3]), ('gates', paths[3:5])]:
        exe = design / f'build/{model}.vvp'
        subprocess.run([str(ROOT / '.tools/bin/iverilog'), '-g2012', '-s', 'tb_vga', '-o', str(exe),
                        str(ROOT / 'tests/tb_vga.v'), *map(str, sources)], check=True, cwd=design)
        for freq, half in [(6.30, '79.365079365'), (6.45, '77.519379845')]:
            dump = design / f'build/{model}_{freq:.2f}.hex'
            log = subprocess.check_output([str(ROOT / '.tools/bin/vvp'), str(exe), '+HALF_NS=' + half,
                                           '+DUMP=' + str(dump)], text=True, cwd=design)
            assert 'PASS: 315017 pixel ticks' in log and 'FAIL' not in log
            assert dump.read_bytes() == expected, (name, model, freq)
            checks.append({'model': model, 'mhz': freq, 'ticks': 315017, 'result': 'PASS'})
            logs.append(log)
    from PIL import Image
    import numpy as np
    dumped = np.array([int(v, 16) for v in dump.read_text().split()], dtype=np.uint8).reshape(525, 200)[:480, :160]
    rgb = np.stack([((dumped >> 4) & 3) * 85, ((dumped >> 2) & 3) * 85, (dumped & 3) * 85], axis=-1)
    Image.fromarray(np.repeat(rgb, 4, axis=1)).save(design / 'build/gates_6.45.png')
    result = {'checks': checks, 'sha256': {str(p.relative_to(ROOT)): sha(p) for p in paths},
              'limitations': 'Unit-delay cell simulation, no routed parasitic timing or monitor test.'}
    (design / 'build/verification.json').write_text(json.dumps(result, indent=2) + '\n')
    (design / 'build/verification.log').write_text('\n'.join(logs))
    print(name + ': four full-frame RTL/final-netlist checks PASS', flush=True)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('action', choices=['generate', 'verify'])
    ap.add_argument('names', nargs='*')
    args = ap.parse_args()
    for name in args.names or MODES:
        (generate if args.action == 'generate' else verify)(name)
