#!/usr/bin/env python3
"""A-only reachable color decode and shared axis predicates; exact image."""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from a_logo_trial import ROOT, SOURCE, PALETTE, reference, covers


def generate(start, mode):
    name = f'a_mask_h{start}_{mode}'
    design = ROOT / 'experiments' / name
    assert not (design / 'out').exists()
    for sub in ('build', 'tests'):
        (design / sub).mkdir(parents=True, exist_ok=True)
    src = ROOT / 'experiments' / f'a_h{start}_v500_x'
    rects = json.loads(SOURCE.read_text())
    reference(rects, design)
    # Check every reachable mask combination against the ordered painter before
    # using A's geometric exclusions to simplify the palette decoder.
    combos = set()
    for yy in range(108):
        for xx in range(128):
            hits = [any(c == co and a <= xx < b and t <= yy < u for c, a, t, b, u in rects)
                    for co in [4, 5, 1, 2, 3]]
            dark, purple, blue, red, cyan = hits
            actual = 63
            for co, hit in zip([4, 5, 1, 2, 3], hits):
                if hit: actual = PALETTE[co]
            bits = [True, not red, not ((blue and not cyan) or (purple and not red)),
                    not (red or (dark and not blue)), not (purple and not (blue or red)),
                    not (blue or cyan or (dark and not red))]
            assert sum(int(b) << i for i, b in enumerate(bits)) == actual
            combos.add(tuple(map(int, hits)))
    logo = (src / 'ishi_logo.v').read_text()
    if mode != 'direct':
        sys.path.insert(0, str(ROOT / '.tools/logic_pyeda'))
        from pyeda.inter import exprvars, And, Or, espresso_exprs

        def erange(v, a, b):
            return Or(*[And(*[(v[i] if val & (1 << i) else ~v[i]) for i in range(8) if mask & (1 << i)])
                        for val, mask in covers(a, b)])

        def vv(e):
            if e.is_zero(): return "1'b0"
            if e.is_one(): return "1'b1"
            s = str(e)
            if s.startswith('Or('): return '(' + ' | '.join(vv(x) for x in e.xs) + ')'
            if s.startswith('And('): return '(' + ' & '.join(vv(x) for x in e.xs) + ')'
            return s

        from collections import defaultdict
        labels, lines = {}, []
        for axis, ia, ib in [('h', 1, 3), ('y', 2, 4)]:
            intervals = sorted({(r[ia], r[ib]) for r in rects})
            v = exprvars(axis, 8)
            fs = []
            for a, b in intervals:
                if axis == 'y':
                    fs.append(erange(v, a + 131, b + 131))
                else:
                    lo, hi = (start - b - 15) % 256, (start - a - 15) % 256
                    fs.append(erange(v, lo, hi) if lo < hi else Or(erange(v, lo, 256), erange(v, 0, hi)))
            sop = espresso_exprs(*fs)
            pos = espresso_exprs(*[(~f).to_dnf() for f in fs])
            for i, (interval, sp, po) in enumerate(zip(intervals, sop, pos)):
                label = f'{axis}_range_{i}'
                labels[(axis, *interval)] = label
                use_pos = mode == 'pos' or (mode == 'mixed' and po.size < sp.size)
                lines.append(f'wire {label} = ' + ('~' + vv(po) if use_pos else vv(sp)) + ';')
        for co in [4, 5, 1, 2, 3]:
            lines.append(f'wire color_{co} = ' + ' | '.join(
                f'({labels[("h", a, b)]} & {labels[("y", t, u)]})' for c, a, t, b, u in rects if c == co) + ';')
        logo = '\n'.join(['`default_nettype none', 'module ishi_logo(input wire [7:0] h,y, output wire [5:0] rgb);',
                          *lines, 'assign rgb = 0;', 'endmodule', '`default_nettype wire', ''])
    decode = '''assign rgb[5] = ~(color_1 | color_3 | (color_4 & ~color_2));
assign rgb[4] = ~(color_5 & ~(color_1 | color_2));
assign rgb[3] = ~(color_2 | (color_4 & ~color_1));
assign rgb[2] = ~((color_1 & ~color_3) | (color_5 & ~color_2));
assign rgb[1] = ~color_2;
assign rgb[0] = 1'b1;'''
    logo, n = re.subn(r'assign rgb = .*?;', decode, logo)
    assert n == 1
    (design / 'ishi_logo.v').write_text('// Generated by scripts/a_mask_trial.py: ' + name + '\n' + logo)
    for filename in ('ishi_vga_core.v', 'config.py'):
        (design / filename).write_bytes((src / filename).read_bytes())
    paths = [Path(__file__), ROOT / 'scripts/a_logo_trial.py', SOURCE, ROOT / 'toolchain.lock.json',
             design / 'config.py', design / 'ishi_vga_core.v', design / 'ishi_logo.v', design / 'tests/expected_frame.hex']
    (design / 'source_manifest.json').write_text(json.dumps({'h_start': start, 'mode': mode,
        'reachable_color_masks': sorted(combos),
        'sha256': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}, indent=2) + '\n')
    print(name, flush=True)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('start', type=int, choices=[63, 79])
    ap.add_argument('mode', choices=['direct', 'sop', 'pos', 'mixed'])
    args = ap.parse_args()
    generate(args.start, args.mode)
