#!/usr/bin/env python3
"""Share complete A row patterns, either per mask or per final RGB bitmap."""
import hashlib
import json
import re
from pathlib import Path
from a_logo_trial import ROOT, SOURCE, PALETTE, reference, spans, raw_range


def generate(start, mode):
    name = f'a_rows_h{start}_{mode}'
    dst = ROOT / 'experiments' / name
    assert not (dst / 'out').exists()
    for sub in ('build', 'tests'):
        (dst / sub).mkdir(parents=True, exist_ok=True)
    src = ROOT / 'experiments' / f'a_h{start}_v500_x'
    rects = json.loads(SOURCE.read_text())
    painted = reference(rects, dst)

    def hx(a, b):
        lo, hi = (start - b - 15) % 256, (start - a - 15) % 256
        if lo < hi: return raw_range('h', lo, hi)
        if hi == 0: return raw_range('h', lo, 256)
        return '(' + raw_range('h', lo, 256) + ' | ' + raw_range('h', 0, hi) + ')'

    def yr(ys):
        return '(' + ' | '.join(raw_range('y', a + 131, b + 131) for a, b, value in spans([y in ys for y in range(108)]) if value) + ')'

    def xr(row):
        runs = [hx(a, b) for a, b, value in spans(row) if value]
        return '(' + ' | '.join(runs) + ')' if runs else "1'b0"

    logo = (src / 'ishi_logo.v').read_text()
    stats = {}
    if mode == 'masks':
        for co in [4, 5, 1, 2, 3]:
            patterns = {}
            for yy in range(108):
                row = tuple(any(c == co and a <= xx < b and t <= yy < u for c, a, t, b, u in rects) for xx in range(128))
                if any(row): patterns.setdefault(row, []).append(yy)
            stats[co] = len(patterns)
            expr = ' |\n    '.join('(' + yr(ys) + ' & ' + xr(row) + ')' for row, ys in patterns.items())
            logo, n = re.subn(f'wire color_{co} = .*?;', f'wire color_{co} = {expr};', logo, flags=re.S)
            assert n == 1
    else:
        patterns = {}
        for yy, row in enumerate(painted):
            if any(row): patterns.setdefault(tuple(row), []).append(yy)
        stats['rgb_rows_excluding_white'] = len(patterns)
        lines = ['`default_nettype none', 'module ishi_logo(input wire [7:0] h,y, output wire [5:0] rgb);']
        for i, (row, ys) in enumerate(patterns.items()):
            lines.append(f'wire sel_{i} = {yr(ys)};')
            for bit in range(1, 6):
                lines.append(f'wire low_{i}_{bit} = ' + xr([not (PALETTE[c] & (1 << bit)) for c in row]) + ';')
        for bit in range(1, 6):
            lines.append(f'assign rgb[{bit}] = ~(' + ' | '.join(f'(sel_{i} & low_{i}_{bit})' for i in range(len(patterns))) + ');')
        lines.extend(["assign rgb[0] = 1'b1;", 'endmodule', '`default_nettype wire', ''])
        logo = '\n'.join(lines)
    (dst / 'ishi_logo.v').write_text('// Generated by scripts/a_row_trial.py: ' + name + '\n' + logo)
    for filename in ('ishi_vga_core.v', 'config.py'):
        (dst / filename).write_bytes((src / filename).read_bytes())
    paths = [Path(__file__), ROOT / 'scripts/a_logo_trial.py', SOURCE, ROOT / 'toolchain.lock.json',
             dst / 'config.py', dst / 'ishi_vga_core.v', dst / 'ishi_logo.v', dst / 'tests/expected_frame.hex']
    (dst / 'source_manifest.json').write_text(json.dumps({'h_start': start, 'mode': mode, 'patterns': stats,
        'sha256': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}, indent=2) + '\n')
    print(name, flush=True)


if __name__ == '__main__':
    for h in [63, 79]:
        for m in ['masks', 'rgb']: generate(h, m)
