#!/usr/bin/env python3
"""A vertical counter offsets, with exactly unchanged external scan order."""
import hashlib
import json
import re
from pathlib import Path
from a_logo_trial import ROOT, SOURCE, reference


def generate(h_start, v_start):
    assert v_start in (0, 496, 512)
    name = f'a_h{h_start}_v{v_start}_x'
    src = ROOT / 'experiments' / f'a_h{h_start}_v500_x'
    dst = ROOT / 'experiments' / name
    assert not (dst / 'source_manifest.json').exists()
    for sub in ('build', 'tests'):
        (dst / sub).mkdir(parents=True, exist_ok=True)
    reference(json.loads(SOURCE.read_text()), dst)
    core = (src / 'ishi_vga_core.v').read_text()
    assert core.count("10'd500") == 3
    for old in (980, 990, 992):
        assert core.count(f"10'd{old}") == 1
    mapping = {500: v_start, 0: (v_start + 524) % 1024,
               980: v_start + 480, 990: v_start + 490, 992: v_start + 492}
    core, count = re.subn(r"10'd(500|980|990|992|0)\b", lambda m: f"10'd{mapping[int(m[1])]}", core)
    assert count == 7
    logo = (src / 'ishi_logo.v').read_text()
    def shift(m):
        value = int(m[2]) + (v_start - 500) // 4
        assert 0 <= value < 256
        return m[1] + str(value)
    logo, count = re.subn(r"(y [<>]=? 8'd)(\d+)", shift, logo)
    assert count > 0
    (dst / 'ishi_vga_core.v').write_text(core)
    (dst / 'ishi_logo.v').write_text('// Generated by scripts/a_vertical_trial.py: ' + name + '\n' + logo)
    (dst / 'config.py').write_bytes((src / 'config.py').read_bytes())
    paths = [Path(__file__), ROOT / 'scripts/a_logo_trial.py', SOURCE, ROOT / 'toolchain.lock.json',
             src / 'ishi_vga_core.v', src / 'ishi_logo.v', dst / 'config.py',
             dst / 'ishi_vga_core.v', dst / 'ishi_logo.v', dst / 'tests/expected_frame.hex']
    (dst / 'source_manifest.json').write_text(json.dumps({'h_start': h_start, 'v_start': v_start,
        'sha256': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}}, indent=2) + '\n')
    print(name, flush=True)


if __name__ == '__main__':
    for h, v in [(63, 512), (79, 512), (63, 0), (63, 496)]: generate(h, v)
