#!/usr/bin/env python3
"""Generate isolated H-origin +80 logo logic combinations."""
from pathlib import Path
import json, sys, re
P=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(P/'.tools/logic_pyeda'))
from pyeda.inter import exprvars,And,Or,espresso_exprs
ns={'__file__':str(P/'scripts/logic_generate.py')}
src=(P/'scripts/logic_generate.py').read_text();exec(src[:src.index('for mode in')],ns)
rects=ns['rects']; covers=ns['covers']; masked=ns['masked']; rgb=ns['rgb_direct']
HO=int(sys.argv[1]) if len(sys.argv)>1 else 80
VO=int(sys.argv[2]) if len(sys.argv)>2 else 0
YO=VO//4
def verilog(e):
 if e.is_zero(): return "1'b0"
 if e.is_one(): return "1'b1"
 s=str(e)
 if s.startswith('Or('): return '('+' | '.join(verilog(a) for a in e.xs)+')'
 if s.startswith('And('): return '('+' & '.join(verilog(a) for a in e.xs)+')'
 return s
def intervals(a,b,off):
 a=(a+off)%256;b=(b+off)%256
 return [(a,b)] if a<b else ([(a,256),(0,b)] if b else [(a,256)])
def range_expr(v,a,b,off):
 return Or(*[And(*[(v[i] if val&(1<<i) else ~v[i]) for i in range(8) if mask&(1<<i)]) for lo,hi in intervals(a,b,off) for val,mask in covers(lo,hi)])
def iv(signal,a,b,off,width):
 n=1<<width;a=(a+off)%n;b=(b+off)%n
 if a<b:return f"(({signal} >= {width}'d{a}) && ({signal} < {width}'d{b}))"
 if b==0:return f"({signal} >= {width}'d{a})"
 return f"(({signal} >= {width}'d{a}) || ({signal} < {width}'d{b}))"
def core_offset(ho,vo):
 c=(P/'rtl/ishi_vga_core.v').read_text()
 c=c.replace("h <= 8'd0;",f"h <= 8'd{ho%256};").replace("h == 8'd199",f"h == 8'd{(199+ho)%256}")
 c=c.replace("v <= 10'd0;",f"v <= 10'd{vo%1024};").replace("v == 10'd524",f"v == 10'd{(524+vo)%1024}").replace("? 10'd0 :",f"? 10'd{vo%1024} :")
 c=c.replace("(h < 8'd160)",iv('h',0,160,ho,8)).replace("(v < 10'd480)",iv('v',0,480,vo,10))
 c=c.replace("((h >= 8'd164) && (h < 8'd188))",iv('h',164,188,ho,8)).replace("((v >= 10'd490) && (v < 10'd492))",iv('v',490,492,vo,10))
 return c
def new(name,logo_lines):
 d=P/'experiments'/('combine_'+name);d.mkdir(parents=True,exist_ok=True);(d/'build').mkdir(exist_ok=True)
 if not (d/'tests').exists(): (d/'tests').symlink_to('../../tests',target_is_directory=True)
 (d/'ishi_logo.v').write_text('// Generated by scripts/combine_generate.py\n`default_nettype none\nmodule ishi_logo(input wire [7:0] h,y, output wire [5:0] rgb);\n'+'\n'.join(logo_lines)+'\nendmodule\n`default_nettype wire\n')
 (d/'ishi_vga_core.v').write_text(core_offset(HO,VO))
 cfg=(P/'experiments/arch_offset_h80/config.py').read_text().replace("SYN_RTL = ['ishi_vga_core.v', 'ishi_logo.v']", "SYN_RTL = ['ishi_vga_core.v', 'ishi_logo.v']")
 (d/'config.py').write_text(cfg)
 (d/'offset.json').write_text(json.dumps({'h':HO,'y':YO})+'\n')
 print(d.name)
# Direct RGB, ordinary comparisons on split wrapped intervals.
lines=[]
for c in [4,5,1,2,3]:
 terms=[]
 for co,a,b,x,yend in rects:
  if co!=c: continue
  for lo,hi in intervals(a,x,HO):
   for yl,yh in intervals(b,yend,YO):
    hx=f"(h>=8'd{lo})" if hi==256 else f"((h>=8'd{lo}) & (h<8'd{hi}))"
    yy=f"(y>=8'd{yl})" if yh==256 else f"((y>=8'd{yl}) & (y<8'd{yh}))"
    terms.append(f'({hx} & {yy})')
 lines.append(f'wire color_{c} = '+' | '.join(terms)+';')
new(f'direct_bounds_h{HO}_v{VO}',lines+rgb())
# Direct RGB, dyadic masked split intervals.
lines=[]
for c in [4,5,1,2,3]:
 terms=[]
 for co,a,b,x,y in rects:
  if co!=c:continue
  for lo,hi in intervals(a,x,HO):
   for yl,yh in intervals(b,y,YO):terms.append(f'({masked("h",lo,hi)} & {masked("y",yl,yh)})')
 lines.append(f'wire color_{c} = '+' | '.join(terms)+';')
new(f'direct_masked_h{HO}_v{VO}',lines+rgb())
# Minimize each shifted range predicate as a complemented POS, retaining geometry.
lines=[];labels={}
for axis,ix,off in [('h',(1,3),HO),('y',(2,4),YO)]:
 ivs=sorted(set((r[ix[0]],r[ix[1]]) for r in rects));v=exprvars(axis,8)
 fs=[range_expr(v,a,b,off) for a,b in ivs]
 neg=espresso_exprs(*[(~f).to_dnf() for f in fs])
 for i,((a,b),f) in enumerate(zip(ivs,neg)):
  label=f'{axis}_range_{i}';labels[(axis,a,b)]=label;lines.append(f'wire {label} = ~{verilog(f)};')
for c in [4,5,1,2,3]:
 lines.append(f'wire color_{c} = '+' | '.join(f'({labels[("h",a,x)]} & {labels[("y",b,y)]})' for co,a,b,x,y in rects if co==c)+';')
new(f'axis_pos_h{HO}_v{VO}',lines+rgb())
# Y-MSB-first then H-MSB-first shared ROBDD of the shifted exact pixel map.
pal=[63,27,53,31,23,43];pixels=[[63]*256 for _ in range(256)]
for c,a,b,x,y in rects:
 for yy in range(b,y): pixels[yy][a:x]=[pal[c]]*(x-a)
order=list(range(7,-1,-1))+list(range(15,7,-1)); table=[]
for yy in range(256):
 for hh in range(256): table.append(pixels[(yy-YO)%256][(hh-HO)%256])
nodes={};seq=[];cache={}
def node(depth,values):
 if not any(values):return 0
 if all(values):return 1
 key=(depth,values)
 if key in cache:return cache[key]
 n=len(values)//2;lo=node(depth+1,values[:n]);hi=node(depth+1,values[n:])
 if lo==hi:r=lo
 else:
  nk=(order[depth],lo,hi)
  if nk not in nodes:nodes[nk]=len(nodes)+2;seq.append(nk)
  r=nodes[nk]
 cache[key]=r;return r
outputs=[node(0,bytes((v>>bit)&1 for v in table)) for bit in range(6)]
def ref(i):return "1'b"+str(i) if i<2 else f'n{i}'
lines=[]
for (bit,lo,hi),idx in nodes.items():
 v=f'h[{bit-8}]' if bit>=8 else f'y[{bit}]';lines.append(f'wire n{idx} = {v} ? {ref(hi)} : {ref(lo)};')
for i,idx in enumerate(outputs):lines.append(f'assign rgb[{i}] = {ref(idx)};')
new(f'bdd_yx_msb_h{HO}_v{VO}',lines)
