#!/usr/bin/env python3
"""Compile the approved ordered rectangles into parallel color masks, no ROM."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
rects = json.loads((ROOT/'assets/logo_rectangles.json').read_text())
assert len(rects) == 21  # Selected B: retain only the two horizontal outline bars
palette = [0b111111, 0b011011, 0b110101, 0b011111, 0b010111, 0b101011]
# The source is ordered by layers; combining rectangles within a layer is exact.
order = list(dict.fromkeys(r[0] for r in rects))
assert order == [4,5,1,2,3]
lines = ['// Generated by scripts/generate_logo_rtl.py; source: assets/logo_rectangles.json',
         '`default_nettype none',
         'module ishi_logo(input wire [7:0] h, input wire [7:0] y, output reg [5:0] rgb);']
for color in order:
    terms=[]
    for c,x0,y0,x1,y1 in rects:
        assert 0 <= x0 < x1 <= 128 and 0 <= y0 < y1 <= 108
        if c==color:
            terms.append(f"((h >= 8'd{x0+16}) && (h < 8'd{x1+16}) && (y >= 8'd{y0+6}) && (y < 8'd{y1+6}))")
    lines.append(f'    wire color_{color} =\n        '+' |\n        '.join(terms)+';')
lines += ['    always @* begin', f"        rgb = 6'b{palette[0]:06b};"]
for i,c in enumerate(reversed(order)):
    lines.append(f"        {'if' if i==0 else 'else if'} (color_{c}) rgb = 6'b{palette[c]:06b};")
lines += ['    end','endmodule','`default_nettype wire','']
(ROOT/'rtl/ishi_logo.v').write_text('\n'.join(lines))
print(f'Generated {len(rects)} rectangles in {len(order)} parallel masks, 6 palette colors.')
