#!/usr/bin/env python3
"""Exact B-logo alternate combinational forms; isolated output only."""
from pathlib import Path
import json,itertools,sys
P=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(P/'.tools/logic_pyeda'))
from pyeda.inter import exprvars,And,Or,espresso_exprs
rects=json.loads((P/'assets/logo_rectangles.json').read_text())
rects=[(c,x0+16,y0+6,x1+16,y1+6) for c,x0,y0,x1,y1 in rects]
pal=[63,27,53,31,23,43]
head=['`default_nettype none','module ishi_logo(input wire [7:0] h,y, output wire [5:0] rgb);']

def config(name):
 return f'''"""Exact-image combinational experiment: {name}."""
from pathlib import Path
import runpy
PROJECT = Path(__file__).resolve().parents[2]
settings = runpy.run_path(str(PROJECT/'config.py'))
globals().update({{k:v for k,v in settings.items() if not k.startswith('__')}})
SYN_RTL = [str(PROJECT/'rtl/ishi_vga_core.v'), str(PROJECT/'experiments/{name}/ishi_logo.v')]
SYN_TB_RTL = SYN_TB_NET = [str(PROJECT/'tests/tb_vga.v')]
'''
def write(name,lines):
 name='logic_'+name
 b=P/'experiments'/name;b.mkdir(exist_ok=True);(b/'build').mkdir(exist_ok=True)
 if not (b/'tests').exists():(b/'tests').symlink_to('../../tests',target_is_directory=True)
 (b/'config.py').write_text(config(name))
 (b/'ishi_logo.v').write_text('// Generated by scripts/logic_generate.py\n'+'\n'.join(head+lines+['endmodule','`default_nettype wire','']))
 print(name)

def bounds(axis,a,b):return f'(({axis}>=8\'d{a}) & ({axis}<8\'d{b}))'
def covers(a,b):
 result=[]
 while a<b:
  size=(a&-a) if a else 256
  while a+size>b:size//=2
  result.append((a,256-size));a+=size
 return result

def masked(axis,a,b):
 return '('+' | '.join(f"(({axis} & 8'd{mask}) == 8'd{value})" for value,mask in covers(a,b))+')'
def rgb_direct():
 return ['wire dark = color_4 & ~color_2;', 'wire purple = color_5 & ~color_2;',
 'assign rgb = {~(color_1|color_3|dark), ~purple, ~(color_2|dark), ~(color_1|purple), ~color_2, 1\'b1};']
for mode in ['bounds','masked']:
 lines=[];cmp=bounds if mode=='bounds' else masked
 for color in [4,5,1,2,3]:
  lines.append(f'wire color_{color} = '+' | '.join(f'({cmp("h",a,c)} & {cmp("y",b,d)})' for co,a,b,c,d in rects if co==color)+';')
 write('direct_'+mode,lines+rgb_direct())

# Shared constant comparator decompositions. Boolean minimization across all mask
# outputs lets Espresso expose pieces shared by distinct intervals.
h=exprvars('h',8);y=exprvars('y',8)
def expr_range(v,a,b):
 return Or(*[And(*[(v[i] if val&(1<<i) else ~v[i]) for i in range(8) if mask&(1<<i)]) for val,mask in covers(a,b)])
def verilog(e):
 if e.is_zero():return "1'b0"
 if e.is_one():return "1'b1"
 s=str(e)
 if s.startswith('Or('):return '('+' | '.join(verilog(a) for a in e.xs)+')'
 if s.startswith('And('):return '('+' & '.join(verilog(a) for a in e.xs)+')'
 return s
colors=[]
for color in [4,5,1,2,3]:
 colors.append(Or(*[expr_range(h,a,c)&expr_range(y,b,d) for co,a,b,c,d in rects if co==color]).to_dnf())
mins=espresso_exprs(*colors)
write('espresso_colors',[f'wire color_{c} = {verilog(e)};' for c,e in zip([4,5,1,2,3],mins)]+rgb_direct())

# Compute direct active-low RGB as horizontal runs, avoiding complement-to-DNF
# expansion. This is only an offline generator; no ROM is synthesized.
pixels=[[63]*256 for _ in range(256)]
for co,a,b,c,d in rects:
 for yy in range(b,d): pixels[yy][a:c]=[pal[co]]*(c-a)
low=[]
for bit in range(1,6):
 runs={}
 for yy,row in enumerate(pixels):
  start=None
  for xx,val in enumerate(row+[63]):
   hit=not val&(1<<bit)
   if hit and start is None:start=xx
   if not hit and start is not None:
    runs.setdefault((start,xx),[]).append(yy);start=None
 terms=[]
 for (a,b),ys in runs.items():
  start=prev=ys[0]
  for yy in ys[1:]+[999]:
   if yy==prev+1:prev=yy;continue
   terms.append(expr_range(h,a,b)&expr_range(y,start,prev+1))
   start=prev=yy
 low.append(Or(*terms).to_dnf())
mins=espresso_exprs(*low)
write('espresso_rgb',[f'assign rgb[{i}] = ~{verilog(e)};' for i,e in enumerate(mins,1)]+["assign rgb[0]=1'b1;"])

# Factor red text by equal X intervals and by equal Y intervals, keeping painted bands.
for orientation in ['x','y']:
 lines=[]
 for color in [4,5,1,2,3]:
  groups={}
  for co,a,b,c,d in rects:
   if co!=color:continue
   k=(a,c) if orientation=='x' else (b,d)
   groups.setdefault(k,[]).append((b,d) if orientation=='x' else (a,c))
  a1,a2=('h','y') if orientation=='x' else ('y','h')
  lines.append(f'wire color_{color} = '+' | '.join('('+masked(a1,*k)+' & ('+' | '.join(masked(a2,*r) for r in ranges)+'))' for k,ranges in groups.items())+';')
 write('factor_'+orientation,lines+rgb_direct())
