/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module letter_scan_patch(clk, frame_end_n, h4, h5, red, green, blue, green_new, blue_new);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [2:0] _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input blue;
  wire blue;
  output blue_new;
  wire blue_new;
  input clk;
  wire clk;
  input frame_end_n;
  wire frame_end_n;
  input green;
  wire green;
  output green_new;
  wire green_new;
  input h4;
  wire h4;
  input h5;
  wire h5;
  wire [6:0] phase;
  input red;
  wire red;
  XNOR2 _23_ (
    .A(frame_end_n),
    .B(phase[0]),
    .Y(_00_[0])
  );
  INV_X2 _24_ (
    .A(frame_end_n),
    .Y(_04_)
  );
  NAND2 _25_ (
    .A(_04_),
    .B(phase[0]),
    .Y(_05_)
  );
  XNOR2 _26_ (
    .A(phase[1]),
    .B(_05_),
    .Y(_00_[1])
  );
  NAND3 _27_ (
    .A(_04_),
    .B(phase[1]),
    .C(phase[0]),
    .Y(_06_)
  );
  XNOR2 _28_ (
    .A(phase[2]),
    .B(_06_),
    .Y(_00_[2])
  );
  AND4_X1 _29_ (
    .A(_04_),
    .B(phase[1]),
    .C(phase[0]),
    .D(phase[2]),
    .Y(_07_)
  );
  XOR2 _30_ (
    .A(phase[3]),
    .B(_07_),
    .Y(_00_[3])
  );
  INV_X1 _31_ (
    .A(red),
    .Y(_08_)
  );
  XOR2 _32_ (
    .A(phase[5]),
    .B(h5),
    .Y(_09_)
  );
  XOR2 _33_ (
    .A(phase[4]),
    .B(h4),
    .Y(_10_)
  );
  NAND2 _34_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  NOR4 _35_ (
    .A(_08_),
    .B(blue),
    .C(phase[6]),
    .D(_11_),
    .Y(_12_)
  );
  OR2 _36_ (
    .A(green),
    .B(_12_),
    .Y(green_new)
  );
  OR2 _37_ (
    .A(blue),
    .B(_12_),
    .Y(blue_new)
  );
  NAND2 _38_ (
    .A(phase[3]),
    .B(_07_),
    .Y(_13_)
  );
  MUX2 _39_ (
    .A(_16_[0]),
    .B(phase[4]),
    .S(_13_),
    .Y(_01_)
  );
  NAND3 _40_ (
    .A(phase[4]),
    .B(phase[3]),
    .C(_07_),
    .Y(_14_)
  );
  XNOR2 _41_ (
    .A(phase[5]),
    .B(_14_),
    .Y(_02_)
  );
  NAND4 _42_ (
    .A(phase[4]),
    .B(phase[3]),
    .C(phase[5]),
    .D(_07_),
    .Y(_15_)
  );
  XNOR2 _43_ (
    .A(phase[6]),
    .B(_15_),
    .Y(_03_)
  );
  DFF _44_ (
    .CK(clk),
    .D(_01_),
    .Q(phase[4]),
    .QB(_16_[0])
  );
  DFF _45_ (
    .CK(clk),
    .D(_02_),
    .Q(phase[5]),
    .QB(_18_)
  );
  DFF _46_ (
    .CK(clk),
    .D(_03_),
    .Q(phase[6]),
    .QB(_19_)
  );
  DFF _47_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(phase[0]),
    .QB(_20_)
  );
  DFF _48_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(phase[1]),
    .QB(_21_)
  );
  DFF _49_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(phase[2]),
    .QB(_22_)
  );
  DFF _50_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(phase[3]),
    .QB(_17_)
  );
  assign _16_[2:1] = phase[6:5];
endmodule
